from __future__ import annotations

from typing import Optional, Protocol

from rinsehq.domain.entities.account import BusinessInfo, PersonalInfo, SubAdmin
from rinsehq.domain.entities.customer import Customer
from rinsehq.domain.entities.invoice import Invoice
from rinsehq.domain.entities.service import Service, ServicesConfiguration
from rinsehq.domain.entities.transaction import Transaction
from rinsehq.infrastructure.auth.permissions import PermissionLevel


class CatalogRepository(Protocol):
    async def list_services(
        self, store_id: str, status: str | None = None, category: str | None = None
    ) -> list[Service]: ...

    async def service_summary(self, store_id: str) -> dict: ...

    async def find_service(self, service_id: str, store_id: str) -> Optional[Service]: ...

    async def create_service(self, store_id: str, **fields: object) -> Service: ...

    async def update_service(self, service_id: str, store_id: str, **fields: object) -> Optional[Service]: ...

    async def get_config(self, store_id: str) -> ServicesConfiguration: ...

    async def set_config(self, store_id: str, config: ServicesConfiguration) -> ServicesConfiguration: ...

    async def add_config_item(self, store_id: str, section: str, label: str) -> ServicesConfiguration: ...

    async def seed_default_services(self, store_id: str, laundry_modes: list[str]) -> None: ...

    async def increment_service_orders_count(
        self, store_id: str, service_ids: list[str]
    ) -> None: ...

    async def search_customers(self, store_id: str, search: str) -> list[Customer]: ...

    async def list_customers(self, store_id: str, limit: int = 20) -> list[Customer]: ...

    async def upsert_customer(
        self, store_id: str, name: str, email: str, phone: str, address: str
    ) -> Customer: ...


class BillingRepository(Protocol):
    async def create_invoice_for_order(self, order_id: str, store_id: str) -> Invoice: ...

    async def find_invoice(self, invoice_id: str) -> Optional[Invoice]: ...

    async def find_invoice_for_store(self, invoice_id: str, store_id: str) -> Optional[Invoice]: ...

    async def mark_invoice_paid(self, invoice_id: str) -> None: ...

    async def list_transactions(
        self, store_id: str, status: str | None, tx_type: str | None, page: int, limit: int
    ) -> tuple[list[Transaction], int]: ...

    async def find_transaction(self, txn_id: str, store_id: str) -> Optional[Transaction]: ...

    async def create_payment_transaction(self, **fields: object) -> Transaction: ...

    async def create_refund_transaction(self, payment_id: str, reason: str, store_id: str) -> Transaction: ...

    async def revenue_summary(self, store_id: str) -> dict: ...

    async def update_order_payment(self, order_id: str, status: str, method: str) -> None: ...

    async def find_transaction_by_reference(self, reference: str) -> Optional[Transaction]: ...

    async def mark_transaction_successful(
        self,
        transaction_id: str,
        *,
        channel: str = "card",
        fee_kobo: int = 0,
        net_kobo: int = 0,
    ) -> None: ...

    async def find_invoice_by_order_id(self, order_id: str) -> Optional[Invoice]: ...

    async def find_invoice_by_account_ref(self, account_ref: str) -> Optional[Invoice]: ...

    async def mark_transaction_failed(self, transaction_id: str) -> None: ...


class AccountRepository(Protocol):
    async def get_personal(self, user_id: str) -> PersonalInfo: ...

    async def get_business(self, user_id: str) -> BusinessInfo: ...

    async def update_business(self, user_id: str, **fields: object) -> BusinessInfo: ...

    async def update_business_profile_files(
        self, user_id: str, logo_url: str | None, banner_url: str | None, document_url: str | None
    ) -> BusinessInfo: ...

    async def list_sub_admins(self, owner_user_id: str) -> list[SubAdmin]: ...

    async def create_sub_admin(
        self, owner_user_id: str, name: str, email: str, permission_level: PermissionLevel,
        permissions: dict[str, bool], status: str, store_ids: list[str], password: str,
    ) -> SubAdmin: ...

    async def update_sub_admin(self, admin_id: str, owner_user_id: str, **fields: object) -> Optional[SubAdmin]: ...

    async def delete_sub_admin(self, admin_id: str, owner_user_id: str) -> bool: ...
